PACKAGE_NAME="snd-hda-codec-hsfmodem"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="snd-hda-codec-hsfmodem"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
