#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the CFGMGR_CODE -> NVM file name table.

    gen_cfgnames.py OUTPUT -- CC [CFLAGS...]

Runs the C preprocessor over configcodes.h with the blob ABI flags, so the
conditional enumerators match the blob build, and writes C designated
initialisers. Each code's NVM file is named after its enumerator without the
CFGMGR_ prefix, with two legacy rules:
  * several enumerators alias one value (NRINGS_TO_ANSWER = SREG+0); such a
    value is named after its first enumerator;
  * a few codes never had a name (the legacy driver fell back to a
    "code_<n>\\n" file that cannot exist); they are left out.
"""
import re
import subprocess
import sys

UNNAMED = {
    "BLAM_STATE", "CADENCE_BASE", "SETTINGS_NILECTRL_DESCRIPTION",
    "TONEB_980_PARAMS", "TONE_CAS", "TONE_DTMF", "V8BTONEB_2225_PARAMS",
    "V8BTONEC_2100_PARAMS",
}


def enumerators(text):
    m = re.search(r"typedef\s+enum\s+tagCFGMGR_CODE\s*\{(.*?)\}\s*CFGMGR_CODE\s*;", text, re.S)
    if not m:
        sys.exit("CFGMGR_CODE enum not found")
    values, nxt = {}, 0
    for item in m.group(1).split(","):
        name, _, expr = (part.strip() for part in item.partition("="))
        if not name:
            continue
        if not re.fullmatch(r"CFGMGR_[A-Za-z0-9_]+", name):
            sys.exit(f"unexpected enumerator {name!r}")
        if expr:
            em = re.fullmatch(r"(?:(CFGMGR_[A-Za-z0-9_]+)\s*(?:\+\s*)?)?(0[xX][0-9a-fA-F]+|\d+)?", expr)
            if not em or not (em.group(1) or em.group(2)):
                sys.exit(f"cannot evaluate {name} = {expr}")
            base = values[em.group(1)] if em.group(1) else 0
            nxt = base + (int(em.group(2), 0) if em.group(2) else 0)
        values[name] = nxt
        yield name, nxt
        nxt += 1


def main():
    if len(sys.argv) < 4 or sys.argv[2] != "--":
        sys.exit(__doc__)
    out, cmd = sys.argv[1], sys.argv[3:]
    pre = subprocess.run(cmd + ["-E", "-P", "-x", "c", "-"], input='#include "configcodes.h"\n',
                         capture_output=True, text=True)
    if pre.returncode:
        sys.exit(pre.stderr)
    seen = set()
    lines = ["/* Generated by gen_cfgnames.py - do not edit. */"]
    for name, value in enumerators(pre.stdout):
        short = name[len("CFGMGR_"):]
        if value in seen:
            continue
        seen.add(value)
        if short not in UNNAMED:
            lines.append(f'\t[{name}] = "{short}",')
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
