#!/bin/sh
# SPDX-License-Identifier: MIT
# Build the codec driver against a pristine kernel.org tree.
#   ci/kernel-build.sh VERSION ARCH [WORKDIR]     e.g. 7.2.6 i386
set -eu
ver=$1
arch=$2
work=${3:-/tmp/hsf-kbuild}
repo=$(cd "$(dirname "$0")/.." && pwd)
major=${ver%%.*}
src=$work/linux-$ver
out=$work/out-$ver-$arch

mkdir -p "$work"
if [ ! -d "$src" ]; then
	curl -fsSL "https://cdn.kernel.org/pub/linux/kernel/v$major.x/linux-$ver.tar.xz" | tar -xJ -C "$work"
fi
make -s -C "$src" O="$out" ARCH="$arch" defconfig
"$src/scripts/config" --file "$out/.config" \
	-e SOUND -e SND -e SND_PCI -e SND_HWDEP -m SND_HDA_INTEL -e SND_HDA_HWDEP
make -s -C "$src" O="$out" ARCH="$arch" olddefconfig
grep -q '^CONFIG_SND_HDA_INTEL=[ym]' "$out/.config" || { echo "SND_HDA_INTEL not enabled" >&2; exit 1; }
make -s -C "$src" O="$out" ARCH="$arch" -j"$(nproc)" modules_prepare
# Module.symvers is not generated by modules_prepare, so unresolved symbols
# are only warnings here; everything else must compile without warnings.
make -C "$out" ARCH="$arch" M="$repo/kernel" MO="$out/hsfmodem" W=1 KBUILD_MODPOST_WARN=1 modules 2>&1 |
	tee "$out/hsfmodem-build.log"
if grep -E '(warning|error):' "$out/hsfmodem-build.log" | grep -v 'modpost: .* undefined'; then
	echo "compiler warnings or errors" >&2
	exit 1
fi
test -f "$out/hsfmodem/snd-hda-codec-hsfmodem.ko"
echo "OK: snd-hda-codec-hsfmodem built for Linux $ver ($arch)"
