name: Makefile CI

on:
  push:
    branches: [ "master", "wip" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: configure
#      run: ./configure

    - name: Apt update
      run: sudo apt update

    - name: Install dependencies
      run: sudo apt install build-essential debhelper -y

    - name: Compile .deb
      run: sudo make debprecomp
