name: Makefile CI

on:
  push:
    branches: [ "master", "wip" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: apt install debhelper -y

    - name: Compile .deb
      run: make debprecomp
